/**
 * @deprecated Seed data for SQL migration only — runtime shop loads from
 * Supabase `gh_shop_products` (see `src/lib/shop/db.ts`). Do not import SEED
 * into storefront code.
 *
 * Official Gamerholic apparel catalog — Gamer & Gamerholic tees + hoodies.
 * Classic → if-you-know-you-know. Hoodies ≥ $49.
 */

import { FABRIC, type ShopProduct } from "./types";

const now = () => new Date().toISOString();

const SIZES = ["S", "M", "L", "XL", "2XL"] as const;
const SIZE_VAR = { name: "Size", options: [...SIZES] };
const COLORS_DARK = {
  name: "Color",
  options: ["Black", "Night Purple", "Arena Charcoal"],
};
const COLORS_TEE = {
  name: "Color",
  options: ["Black", "Night Purple", "Volt", "White"],
};

function p(
  partial: Omit<ShopProduct, "createdAt" | "updatedAt" | "slug" | "category"> & {
    slug?: string;
    category?: ShopProduct["category"];
  },
): ShopProduct {
  const t = now();
  const slug =
    partial.slug ||
    partial.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
  return {
    ...partial,
    category: partial.category ?? "apparel",
    slug,
    createdAt: t,
    updatedAt: t,
  };
}


/** Product photos: front / back / side (composited from print pack + blank garment). */
function teeViews(design: string): string[] {
  return [
    `/shop/products/tees/${design}-front.jpg`,
    `/shop/products/tees/${design}-back.jpg`,
    `/shop/products/tees/${design}-side.jpg`,
  ];
}

function hoodViews(design: string, opts?: { zip?: boolean }): string[] {
  if (opts?.zip) {
    return [
      `/shop/products/hoodies/${design}-zip-front.jpg`,
      `/shop/products/hoodies/${design}-back.jpg`,
      `/shop/products/hoodies/${design}-front.jpg`,
    ];
  }
  return [
    `/shop/products/hoodies/${design}-front.jpg`,
    `/shop/products/hoodies/${design}-back.jpg`,
    `/shop/products/hoodies/${design}-zip-front.jpg`,
  ];
}


/**
 * Full apparel seed. Prices: tees $29–$89, hoodies $49–$189.
 */
export const SEED_PRODUCTS: ShopProduct[] = [
  // ── Classic tees ─────────────────────────────────────────
  p({
    id: "prod-tee-gamer-classic",
    name: "Gamer Classic Wordmark Tee",
    description: [
      "The everyday identity piece. Clean GAMER wordmark, chest center — readable across a lobby or a LAN hall.",
      "",
      FABRIC.teeCore,
      "Fit: retail unisex, true to size. Slightly tapered shoulder.",
    ].join("\n"),
    priceUsd: 34,
    compareAtUsd: 42,
    images: teeViews("gamer"),
    variants: [SIZE_VAR, COLORS_TEE],
    stock: 200,
    sku: "GH-TEE-GAMER-CLS",
    supplierNote: "Combed cotton blank + DTG/screen from print pack",
    published: true,
    featured: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes:
      "Chest center, max width 11–12in. White or volt ink on dark; black ink on white. Vector print pack.",
  }),
  p({
    id: "prod-tee-gamerholic-classic",
    name: "Gamerholic Classic Wordmark Tee",
    description: [
      "Full GAMERHOLIC lockup in display type. Official brand line — the one you wear when the booth has your name on it.",
      "",
      FABRIC.teeCore,
      "Fit: retail unisex. Pair with black bottoms for stage / stream cam.",
    ].join("\n"),
    priceUsd: 38,
    compareAtUsd: 48,
    images: teeViews("gamerholic"),
    variants: [SIZE_VAR, COLORS_TEE],
    stock: 180,
    sku: "GH-TEE-GH-CLS",
    supplierNote: "Combed cotton blank + DTG/screen from print pack",
    published: true,
    featured: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes:
      "Chest center, max width 12in. Volt (#a3ff3d) preferred on black; white on night purple.",
  }),
  p({
    id: "prod-tee-power-g",
    name: "Power-G Mark Tee",
    description: [
      "Minimal power-G app mark only — no wordmark noise. Looks like a label, hits like a brand.",
      "",
      FABRIC.teeCore,
      "Fit: true unisex. Left-chest mark placement (3in).",
    ].join("\n"),
    priceUsd: 32,
    images: teeViews("power-g"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 220,
    sku: "GH-TEE-MARK",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/power-g-mark.svg",
    printFontFamily: "n/a — mark only",
    printText: "",
    printNotes: "Left chest 3in mark. Single-color volt or white.",
  }),
  p({
    id: "prod-tee-i-win",
    name: "I Win For A Living Tee",
    description: [
      "House slogan in clean heading type. Classic arrogance, correctly spelled.",
      "",
      FABRIC.teeCore,
      "Fit: retail unisex.",
    ].join("\n"),
    priceUsd: 36,
    images: teeViews("i-win"),
    variants: [SIZE_VAR, COLORS_TEE],
    stock: 150,
    sku: "GH-TEE-IWIN",
    published: true,
    featured: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/i-win-for-a-living.svg",
    printFontFamily: "Orbitron",
    printText: "I WIN FOR A LIVING",
    printNotes: "Chest center stacked 3 lines or single line 12in max.",
  }),
  p({
    id: "prod-tee-prize",
    name: "Prize Magenta Wordmark Tee",
    description: [
      "GAMERHOLIC in prize-magenta energy. Looks expensive on stream lights.",
      "",
      FABRIC.teePremium,
      "Fit: slightly relaxed shoulder.",
    ].join("\n"),
    priceUsd: 44,
    compareAtUsd: 54,
    images: teeViews("gamerholic-prize"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black"] }],
    stock: 120,
    sku: "GH-TEE-PRIZE",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gamerholic-wordmark-prize.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Prize magenta (#f43fa8) on black only. Chest 12in.",
  }),

  // ── Premium / heavy tees ─────────────────────────────────
  p({
    id: "prod-tee-gamer-boxy",
    name: "Gamer Boxy Heavy Tee",
    description: [
      "Street-cut boxy GAMER tee — drop shoulder, heavier hand, looks intentional on camera.",
      "",
      FABRIC.teeHeavy,
      "Fit: oversized boxy. Size down for closer fit.",
    ].join("\n"),
    priceUsd: 48,
    images: teeViews("gamer"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 100,
    sku: "GH-TEE-GAMER-BOX",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes: "Slightly larger chest hit OK on boxy blank (up to 13in).",
  }),
  p({
    id: "prod-tee-gh-premium",
    name: "Gamerholic Organic Premium Tee",
    description: [
      "Organic cotton, garment-washed. Full wordmark with subtle volt underline.",
      "",
      FABRIC.teePremium,
      "Fit: modern retail. Soft from first wear.",
    ].join("\n"),
    priceUsd: 52,
    images: teeViews("gamerholic"),
    variants: [SIZE_VAR, COLORS_TEE],
    stock: 90,
    sku: "GH-TEE-GH-ORG",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Soft-hand or waterbase preferred on organic blank.",
  }),
  p({
    id: "prod-tee-longline",
    name: "Arena Longline Gamer Tee",
    description: [
      "Extended hem longline with GAMER spine print option (front wordmark + rear vertical).",
      "",
      FABRIC.teeHeavy,
      "Fit: longline unisex. Covers belt line for desk / couch sessions.",
    ].join("\n"),
    priceUsd: 46,
    images: teeViews("gamer"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 80,
    sku: "GH-TEE-LONGLINE",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes: "Front chest + optional rear vertical GAMER (spine, 14in tall).",
  }),

  // ── IYKYK tees ───────────────────────────────────────────
  p({
    id: "prod-tee-host-earns",
    name: "Host Earns Tee",
    description: [
      "If you know you know: operators get paid. Front small mark, back “HOST EARNS” lockup.",
      "",
      FABRIC.teeCore,
      "Fit: true unisex.",
    ].join("\n"),
    priceUsd: 39,
    images: teeViews("host-earns"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 110,
    sku: "GH-TEE-HOST",
    published: true,
    featured: true,
    aspect: "square",
    printAssetUrl: "/shop/print/host-earns.svg",
    printFontFamily: "Orbitron",
    printText: "HOST EARNS",
    printNotes: "Back print primary (12in). Front optional 3in power-G.",
  }),
  p({
    id: "prod-tee-fail-bank",
    name: "Fail Bank Tee",
    description: [
      "Arcade coded. “FAILS PAY THE CROWN” micro-copy under a small cabinet glyph. For high-score landlords.",
      "",
      FABRIC.teeCore,
      "Fit: true unisex.",
    ].join("\n"),
    priceUsd: 38,
    images: teeViews("fail-bank"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 100,
    sku: "GH-TEE-FAIL",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/fail-bank.svg",
    printFontFamily: "Share Tech Mono",
    printText: "FAILS PAY THE CROWN",
    printNotes: "Left chest glyph + center line or back stack. Mono font intentional.",
  }),
  p({
    id: "prod-tee-escrow",
    name: "Escrow Not Trust Tee",
    description: [
      "On-chain culture shirt. “ESCROW > TRUST” with subtle subaccount hash aesthetic.",
      "",
      FABRIC.teeCore,
      "Fit: true unisex. Instant conversation starter with builders.",
    ].join("\n"),
    priceUsd: 40,
    images: teeViews("escrow"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Arena Charcoal"] }],
    stock: 95,
    sku: "GH-TEE-ESCROW",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/escrow-not-trust.svg",
    printFontFamily: "Share Tech Mono",
    printText: "ESCROW > TRUST",
    printNotes: "Chest center mono. White or volt ink only.",
  }),
  p({
    id: "prod-tee-noncustodial",
    name: "Non-Custodial Tee",
    description: [
      "Wallet is the gamer ID. Clean “NON-CUSTODIAL” stack — no cartoon noise.",
      "",
      FABRIC.teeCore,
    ].join("\n"),
    priceUsd: 36,
    images: teeViews("non-custodial"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 130,
    sku: "GH-TEE-NC",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/non-custodial.svg",
    printFontFamily: "Orbitron",
    printText: "NON-CUSTODIAL",
    printNotes: "Chest center, wide tracking.",
  }),
  p({
    id: "prod-tee-xft",
    name: "XFTs That Fight Tee",
    description: [
      "Dexsta bridge energy. “XFTS THAT FIGHT” + “NFT 2.0” sublabel — for attribute maxxers.",
      "",
      FABRIC.teeCore,
    ].join("\n"),
    priceUsd: 41,
    images: teeViews("xft"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 100,
    sku: "GH-TEE-XFT",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/xfts-that-fight.svg",
    printFontFamily: "Orbitron",
    printText: "XFTS THAT FIGHT",
    printNotes: "Two-line stack; optional NFT 2.0 underline in attr violet.",
  }),
  p({
    id: "prod-tee-monitor",
    name: "Game Monitor Tee",
    description: [
      "For the ones who watch the match and cash the call. “MONITOR” badge front, “REPORT · SETTLE” rear.",
      "",
      FABRIC.teeCore,
    ].join("\n"),
    priceUsd: 37,
    images: teeViews("monitor"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 90,
    sku: "GH-TEE-MON",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/game-monitor.svg",
    printFontFamily: "Orbitron",
    printText: "MONITOR",
    printNotes: "Front badge + back REPORT · SETTLE.",
  }),
  p({
    id: "prod-tee-ggwp",
    name: "GG WP Micro Tee",
    description: [
      "Understated. Tiny “GG WP” left chest — if you know, you already nodded.",
      "",
      FABRIC.teePremium,
    ].join("\n"),
    priceUsd: 35,
    images: teeViews("gg-wp"),
    variants: [SIZE_VAR, COLORS_TEE],
    stock: 160,
    sku: "GH-TEE-GGWP",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gg-wp.svg",
    printFontFamily: "Share Tech Mono",
    printText: "GG WP",
    printNotes: "Left chest 2.5in max. Single color.",
  }),
  p({
    id: "prod-tee-bps",
    name: "Host BPS Tee",
    description: [
      "Nerdy flex: “HOST FEE IN BPS” with a faint basis-points grid. For people who set the cut.",
      "",
      FABRIC.teeCore,
    ].join("\n"),
    priceUsd: 39,
    images: teeViews("host-bps"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Night Purple"] }],
    stock: 85,
    sku: "GH-TEE-BPS",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/host-bps.svg",
    printFontFamily: "Share Tech Mono",
    printText: "HOST FEE IN BPS",
    printNotes: "Chest center mono + optional back grid watermark low opacity.",
  }),
  p({
    id: "prod-tee-stack",
    name: "Stack Quietly Tee",
    description: [
      "No logo scream. Rear “STACK QUIETLY” only — front blank except optional 1in power-G.",
      "",
      FABRIC.teePremium,
    ].join("\n"),
    priceUsd: 42,
    images: teeViews("stack"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 75,
    sku: "GH-TEE-STACK",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/stack-quietly.svg",
    printFontFamily: "Orbitron",
    printText: "STACK QUIETLY",
    printNotes: "Back primary. Front optional micro mark.",
  }),
  p({
    id: "prod-tee-18",
    name: "18+ Arena Tee",
    description: [
      "Compliance chic. Bold “18+” badge + “SKILLED GAMING WHERE LEGAL” line. Matches the footer energy.",
      "",
      FABRIC.teeCore,
    ].join("\n"),
    priceUsd: 33,
    images: teeViews("eighteen"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black"] }],
    stock: 140,
    sku: "GH-TEE-18",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/eighteen-plus.svg",
    printFontFamily: "Orbitron",
    printText: "18+",
    printNotes: "Large 18+ chest; legal line smaller under.",
  }),

  // ── Hoodies (all ≥ $49) ──────────────────────────────────
  p({
    id: "prod-hood-gamer-classic",
    name: "Gamer Classic Hoodie",
    description: [
      "Midweight GAMER wordmark hoodie — daily driver for cold arenas and AC lobbies.",
      "",
      FABRIC.hoodieCore,
      "Fit: unisex standard. Kangaroo pocket. Drawcord hood.",
    ].join("\n"),
    priceUsd: 58,
    compareAtUsd: 72,
    images: hoodViews("gamer"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 120,
    sku: "GH-HOOD-GAMER",
    published: true,
    featured: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes: "Chest center on fleece face. Soft-hand or puff optional.",
  }),
  p({
    id: "prod-hood-gh-classic",
    name: "Gamerholic Classic Hoodie",
    description: [
      "Full GAMERHOLIC wordmark on midweight fleece. The booth standard.",
      "",
      FABRIC.hoodieCore,
      "Fit: unisex standard.",
    ].join("\n"),
    priceUsd: 62,
    compareAtUsd: 78,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 110,
    sku: "GH-HOOD-GH",
    published: true,
    featured: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Chest 11in max on hoodie blank.",
  }),
  p({
    id: "prod-hood-prize",
    name: "Prize Magenta Hoodie",
    description: [
      "Prize-magenta GAMERHOLIC hit on black fleece. Looks lethal under neon.",
      "",
      FABRIC.hoodieCore,
    ].join("\n"),
    priceUsd: 64,
    images: hoodViews("gamerholic-prize"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black"] }],
    stock: 90,
    sku: "GH-HOOD-PRIZE",
    published: true,
    featured: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gamerholic-wordmark-prize.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Prize magenta ink on black only.",
  }),
  p({
    id: "prod-hood-i-win",
    name: "I Win For A Living Hoodie",
    description: [
      "Slogan hoodie. Front small power-G, back full “I WIN FOR A LIVING”.",
      "",
      FABRIC.hoodieCore,
    ].join("\n"),
    priceUsd: 66,
    images: hoodViews("i-win"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 100,
    sku: "GH-HOOD-IWIN",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/i-win-for-a-living.svg",
    printFontFamily: "Orbitron",
    printText: "I WIN FOR A LIVING",
    printNotes: "Back print hero; front micro mark.",
  }),
  p({
    id: "prod-hood-heavy-gamer",
    name: "Gamer Heavyweight Hoodie",
    description: [
      "Dense 12–14 oz fleece. GAMER mark holds structure — travel hoodie that still looks sharp day three of a lan.",
      "",
      FABRIC.hoodieHeavy,
      "Fit: slightly roomy for layers.",
    ].join("\n"),
    priceUsd: 79,
    compareAtUsd: 96,
    images: hoodViews("gamer"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 70,
    sku: "GH-HOOD-HVY-GAMER",
    published: true,
    featured: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes: "Heavy fleece — prefer plastisol or thick soft-hand.",
  }),
  p({
    id: "prod-hood-heavy-gh",
    name: "Gamerholic Heavyweight Hoodie",
    description: [
      "Same heavy fleece chassis with full Gamerholic wordmark. Winter circuit kit.",
      "",
      FABRIC.hoodieHeavy,
    ].join("\n"),
    priceUsd: 84,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 65,
    sku: "GH-HOOD-HVY-GH",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Chest center; volt ink recommended on black.",
  }),
  p({
    id: "prod-hood-zip-gh",
    name: "Gamerholic Full-Zip Hoodie",
    description: [
      "Full-zip for booth-to-street transitions. Left-chest mark + sleeve hit optional.",
      "",
      FABRIC.hoodieZip,
      "Fit: athletic unisex.",
    ].join("\n"),
    priceUsd: 89,
    images: hoodViews("power-g", { zip: true }),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 80,
    sku: "GH-HOOD-ZIP-GH",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/power-g-mark.svg",
    printFontFamily: "n/a — mark only",
    printText: "",
    printNotes: "Left chest 3.5in mark; optional right sleeve GAMERHOLIC vertical.",
  }),
  p({
    id: "prod-hood-host",
    name: "Host Cut Zip Hoodie",
    description: [
      "IYKYK operator piece. “HOST CUT” back print, power-G front. For people who take bps.",
      "",
      FABRIC.hoodieZip,
    ].join("\n"),
    priceUsd: 94,
    images: hoodViews("host-earns", { zip: true }),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Night Purple"] }],
    stock: 60,
    sku: "GH-HOOD-HOST",
    published: true,
    featured: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/host-earns.svg",
    printFontFamily: "Orbitron",
    printText: "HOST CUT",
    printNotes: "Back HOST CUT; front micro power-G.",
  }),
  p({
    id: "prod-hood-french",
    name: "Gamerholic French Terry Hoodie",
    description: [
      "Premium 100% cotton French terry — loopback luxury, clean face for the wordmark. Not a gym hoodie; a statement layer.",
      "",
      FABRIC.hoodieFrench,
      "Fit: tailored-relaxed. Minimal shrink if washed cold.",
    ].join("\n"),
    priceUsd: 120,
    compareAtUsd: 145,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Arena Charcoal"] }],
    stock: 45,
    sku: "GH-HOOD-FRENCH",
    published: true,
    featured: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Waterbase / soft-hand only on French terry.",
  }),
  p({
    id: "prod-hood-oversized",
    name: "Arena Oversized Hoodie",
    description: [
      "Drop-shoulder oversized with rear GAMERHOLIC and front micro mark. Fashion cut, arena soul.",
      "",
      FABRIC.hoodieHeavy,
      "Fit: oversized — size down for regular.",
    ].join("\n"),
    priceUsd: 88,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 70,
    sku: "GH-HOOD-OVER",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Back oversized print up to 14in; front micro.",
  }),
  p({
    id: "prod-hood-fail-bank",
    name: "Fail Bank Hoodie",
    description: [
      "Arcade landlords only. “FAIL BANK” chest + crown glyph. Warm while the queue fee stacks.",
      "",
      FABRIC.hoodieCore,
    ].join("\n"),
    priceUsd: 68,
    images: hoodViews("fail-bank"),
    variants: [SIZE_VAR, COLORS_DARK],
    stock: 75,
    sku: "GH-HOOD-FAIL",
    published: true,
    aspect: "square",
    printAssetUrl: "/shop/print/fail-bank.svg",
    printFontFamily: "Share Tech Mono",
    printText: "FAIL BANK",
    printNotes: "Chest mono lockup.",
  }),
  p({
    id: "prod-hood-escrow",
    name: "Escrow Hoodie",
    description: [
      "“FUNDS IN ESCROW” subtle chest line. Builder merch that still passes as fashion.",
      "",
      FABRIC.hoodieCore,
    ].join("\n"),
    priceUsd: 69,
    images: hoodViews("escrow"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black"] }],
    stock: 70,
    sku: "GH-HOOD-ESCROW",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/escrow-not-trust.svg",
    printFontFamily: "Share Tech Mono",
    printText: "FUNDS IN ESCROW",
    printNotes: "Low-key chest mono, white ink.",
  }),
  p({
    id: "prod-hood-blackout",
    name: "Blackout Tourney Hoodie",
    description: [
      "Near-black tonal Gamerholic print — if you know you know under stage lights. Heavy fleece, no loud logos from ten feet.",
      "",
      FABRIC.hoodieHeavy,
      "Fit: standard unisex.",
    ].join("\n"),
    priceUsd: 98,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black"] }],
    stock: 50,
    sku: "GH-HOOD-BLKOUT",
    published: true,
    aspect: "tall",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes: "Tonal dark-gray on black (not pure white). Specialty ink.",
  }),
  p({
    id: "prod-hood-volt-zip",
    name: "Volt Trim Zip Hoodie",
    description: [
      "Full-zip with volt-accent drawcords energy and GAMER chest. High-visibility without looking like a jersey.",
      "",
      FABRIC.hoodieZip,
    ].join("\n"),
    priceUsd: 92,
    images: hoodViews("gamer", { zip: true }),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Night Purple"] }],
    stock: 55,
    sku: "GH-HOOD-VOLT-ZIP",
    published: true,
    aspect: "wide",
    printAssetUrl: "/shop/print/gamer-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMER",
    printNotes: "Volt ink chest; contrast cord if blank allows.",
  }),
  p({
    id: "prod-hood-limited",
    name: "Gamerholic Limited Circuit Hoodie",
    description: [
      "Top-tier limited drop: French terry face feel, heavy structure, dual print (chest mark + numbered-style rear line). Priced for collectors and hosts who already made the cut.",
      "",
      FABRIC.hoodieFrench,
      "Fit: modern oversized-leaning. Run small if between sizes → size up.",
    ].join("\n"),
    priceUsd: 168,
    compareAtUsd: 198,
    images: hoodViews("gamerholic"),
    variants: [SIZE_VAR, { name: "Color", options: ["Black", "Night Purple"] }],
    stock: 30,
    sku: "GH-HOOD-LTD",
    published: true,
    featured: true,
    aspect: "square",
    printAssetUrl: "/shop/print/gamerholic-wordmark.svg",
    printFontFamily: "Orbitron",
    printText: "GAMERHOLIC",
    printNotes:
      "Premium placement: chest 10in + rear “CIRCUIT” line. Soft-hand only. Low qty intentional.",
  }),
];

export const APPAREL_SEED_COUNT = SEED_PRODUCTS.length;
